Traceback (most recent call last):
  File "twitter_script.py", line 70, in <module>
    search_twitter('Alcoholics Anonymous')
  File "twitter_script.py", line 64, in search_twitter
    db_name=write_data_to_db(*get_twitter_data(query))
  File "twitter_script.py", line 37, in get_twitter_data
    html_full=return_html_code(url,False)
  File "/home/ubuntu/social_network_extract/check.py", line 38, in return_html_code
    driver = webdriver.PhantomJS(desired_capabilities=dcap)     
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 51, in __init__
    self.service.start()
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service phantomjs

